export const frameworksLogos: Record<string, string> = {
  nextjs: "https://api-frameworks.vercel.sh/framework-logos/next.svg",
  nuxtjs: "https://api-frameworks.vercel.sh/framework-logos/nuxt.svg",
  svelte: "https://api-frameworks.vercel.sh/framework-logos/svelte.svg",
  "create-react-app":
    "https://api-frameworks.vercel.sh/framework-logos/react.svg",
  gatsby: "https://api-frameworks.vercel.sh/framework-logos/gatsby.svg",
  remix: "https://api-frameworks.vercel.sh/framework-logos/remix-no-shadow.svg",
  "react-router":
    "https://api-frameworks.vercel.sh/framework-logos/react-router.svg",
  solidstart: "https://api-frameworks.vercel.sh/framework-logos/solid.svg",
  sveltekit: "https://api-frameworks.vercel.sh/framework-logos/svelte.svg",
  blitzjs: "https://api-frameworks.vercel.sh/framework-logos/blitz.svg",
  astro: "https://api-frameworks.vercel.sh/framework-logos/astro.svg",
  hexo: "https://api-frameworks.vercel.sh/framework-logos/hexo.svg",
  eleventy: "https://api-frameworks.vercel.sh/framework-logos/eleventy.svg",
  "docusaurus-2":
    "https://api-frameworks.vercel.sh/framework-logos/docusaurus.svg",
  docusaurus: "https://api-frameworks.vercel.sh/framework-logos/docusaurus.svg",
  preact: "https://api-frameworks.vercel.sh/framework-logos/preact.svg",
  "solidstart-1": "https://api-frameworks.vercel.sh/framework-logos/solid.svg",
  dojo: "https://api-frameworks.vercel.sh/framework-logos/dojo.png",
  ember: "https://api-frameworks.vercel.sh/framework-logos/ember.svg",
  vue: "https://api-frameworks.vercel.sh/framework-logos/vue.svg",
  scully: "https://api-frameworks.vercel.sh/framework-logos/scullyio-logo.png",
  "ionic-angular": "https://api-frameworks.vercel.sh/framework-logos/ionic.svg",
  angular: "https://api-frameworks.vercel.sh/framework-logos/angular.svg",
  polymer: "https://api-frameworks.vercel.sh/framework-logos/polymer.svg",
  "sveltekit-1": "https://api-frameworks.vercel.sh/framework-logos/svelte.svg",
  "ionic-react": "https://api-frameworks.vercel.sh/framework-logos/ionic.svg",
  gridsome: "https://api-frameworks.vercel.sh/framework-logos/gridsome.svg",
  umijs: "https://api-frameworks.vercel.sh/framework-logos/umi.svg",
  sapper: "https://api-frameworks.vercel.sh/framework-logos/svelte.svg",
  saber: "https://api-frameworks.vercel.sh/framework-logos/saber.svg",
  stencil: "https://api-frameworks.vercel.sh/framework-logos/stencil.svg",
  redwoodjs: "https://api-frameworks.vercel.sh/framework-logos/redwoodjs.svg",
  hugo: "https://api-frameworks.vercel.sh/framework-logos/hugo.svg",
  jekyll: "https://api-frameworks.vercel.sh/framework-logos/jekyll.svg",
  brunch: "https://api-frameworks.vercel.sh/framework-logos/brunch.svg",
  middleman: "https://api-frameworks.vercel.sh/framework-logos/middleman.svg",
  zola: "https://api-frameworks.vercel.sh/framework-logos/zola.png",
  hydrogen: "https://api-frameworks.vercel.sh/framework-logos/hydrogen.svg",
  vite: "https://api-frameworks.vercel.sh/framework-logos/vite.svg",
  vitepress: "https://api-frameworks.vercel.sh/framework-logos/vite.svg",
  vuepress: "https://api-frameworks.vercel.sh/framework-logos/vuepress.png",
  parcel: "https://api-frameworks.vercel.sh/framework-logos/parcel.png",
  fasthtml: "https://api-frameworks.vercel.sh/framework-logos/fasthtml.png",
  "sanity-v3": "https://api-frameworks.vercel.sh/framework-logos/sanity.svg",
  sanity: "https://api-frameworks.vercel.sh/framework-logos/sanity.svg",
  storybook: "https://api-frameworks.vercel.sh/framework-logos/storybook.svg",
  other: "/other-framework.png",
};
