name: Build and deploy Deplit API

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: pnpm install, build, and test in apps/api
        working-directory: apps/api
        run: |
          pnpm install
          pnpm run build

      - name: Zip artifact for deployment
        working-directory: apps/api
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: apps/api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # required for requesting the JWT
      contents: read # required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_75E65E4899F144E1A87806F4F206E524 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_30FF24239D91409BA624673AD125FA42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A9553C245A5E43C9A0A67F03A910554B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "beta-api-deplit"
          slot-name: "Production"
          package: .
